### ISSUE TITLE
Spring boot YML configs are not read

### ISSUE THREAD

**Issue by ValdasK** [zonkyio/embedded-database-spring-test#153]
I am unable to change image which is used for tests when using Spring Boot 2.4.3 + YML configuration.

If I add 

```
zonky:
  test:
    database:
      postgres:
        docker:
          image: postgres:12-alpine

```
into `application.yml`, it get's ignored, and adding breakpoint in `DockerPostgresDatabaseProvider`
```
String dockerImage = environment.getProperty("zonky.test.database.postgres.docker.image", "postgres:11-alpine");
```
shows that `dockerImage` is still `"postgres:11-alpine"`. I think this could be caused that `Environment` does not parse YML, and only works with `.properties`? Would it not be possible to use `@Value` to extract configurations instead?
