### ISSUE TITLE
Use Zonky provider with PostGIS

### ISSUE THREAD

**Issue by cfecherolle** [zonkyio/embedded-database-spring-test#263]
Hi,

Some time ago, I tried using making my PostGIS tests work with Zonky provider but could not, as it seems the image used to run the tests cannot be customized.

I have this configuration:
```
zonky:
  test:
    database:
      postgres:
        docker:
          image: postgis/postgis:11-3.1-alpine
```
Which works well with `provider = DOCKER` but is ignored when `provider = ZONKY`.

I would rather use Zonky because it provides better performance and faster test runs than Docker but, it seems that it is not possible at the moment. Is there a workaround I could use to make it work with PostGIS or other custom images?
